#!/usr/bin/env ruby

rc = system("ruby examples/check.rb")
exit unless rc

system("ruby showme.rb examples/prog01.rb")
system("ruby showme.rb examples/prog02.rb")
system("ruby showme.rb examples/prog03.rb")
system("ruby showme.rb examples/prog04.rb")
system("ruby showme.rb examples/prog05.rb")
system("ruby showme.rb examples/prog06.rb")
system("ruby showme.rb examples/prog07.rb")
