#!/usr/bin/env ruby

mylib = `gem which rubytext`.chomp
examples = mylib.sub(%r[/lib/rubytext.rb], "/examples")

Dir.chdir(examples)

rc = system("ruby check.rb")
exit unless rc

# FIXME 
#   - use names instead of numbers?
#   - convert rt-show into a method?

1.upto(19) do |n|
  next if n == 11  # junk this one
  num = '%02d' % n
  prog = "prog#{num}.rb"
  system("ruby showme.rb #{prog}")
end

