#!/usr/bin/env ruby

def showme(name, up="", mode="pause")
  system("ruby showme.rb #{name}.rb #{mode} #{up}")
end

mylib = `gem which rubytext`.chomp
examples = mylib.sub(%r[/lib/rubytext.rb], "/examples")

Dir.chdir(examples)

rc = system("ruby check.rb")
exit unless rc


  showme("simple_win")
  showme("stdscr")
  showme("stdout_etc")
  showme("detect_rc")
  showme("brackets")
  showme("brack_equal")
  showme("puts_print")
  showme("output_meth")
  showme("win_centering")
  showme("putch")
  showme("sym_navigate")
  showme("effects")
  showme("center_meth")
  showme("topbottom")
  showme("udlr_bang")
  showme("updown_etc")
  showme("home_udlr")
  showme("rcprint")
  showme("go_meth")
  showme("no_border")
  showme("no_scroll")
  showme("window_full")
  showme("ticker_threads", 11)
  showme("simple_menu")

